/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.8
 * Generated at: 2020-07-30 04:05:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class notice_005fwrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1585104544341L));
    _jspx_dependants.put("jar:file:/D:/githubtest/kwonpro_spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/KwonProSpring/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>세종시 프로그래머 온라인 허브</title>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"/resources/css/customer/layout.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("    <style>\r\n");
      out.write("        #visual .content-container{\t\r\n");
      out.write("            height:inherit;\r\n");
      out.write("            display:flex; \r\n");
      out.write("            align-items: center;\r\n");
      out.write("            background: url(\"/resources/images/customer/visual.png\") no-repeat center;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- header 부분 -->\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t\t<div class=\"content-container\">\r\n");
      out.write("\t\t\t<!-- --------------------------- <header> ----------------------------------------->\r\n");
      out.write("\t\t\t<h1 id=\"logo\">\r\n");
      out.write("\t\t\t\t<a href=\"/\"> <img src=\"/resources/images/logo.png\"\r\n");
      out.write("\t\t\t\t\talt=\"KwonPro 온라인\" />\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<section>\r\n");
      out.write("\t\t\t\t<h1 class=\"hidden\">헤더</h1>\r\n");
      out.write("\t\t\t\t<nav id=\"main-menu\">\r\n");
      out.write("\t\t\t\t\t<h1>메인메뉴</h1>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">모임가이드</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">모임선택</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">AnswerIs</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t<section id=\"search-form\">\r\n");
      out.write("\t\t\t\t\t\t<h1>강좌검색 폼</h1>\r\n");
      out.write("\t\t\t\t\t\t<form action=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t<legend>모임검색필드</legend>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>모임검색</label> <input type=\"text\" name=\"q\" value=\"\" /> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"submit\" value=\"검색\" />\r\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- --------------------------- <visual> --------------------------------------- -->\r\n");
      out.write("\t<!-- visual 부분 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"visual\">\r\n");
      out.write("\t\t<div class=\"content-container\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- --------------------------- <body> --------------------------------------- -->\r\n");
      out.write("\t<div id=\"body\">\r\n");
      out.write("\t\t<div class=\"content-container clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- --------------------------- aside --------------------------------------- -->\r\n");
      out.write("\t\t\t<!-- aside 부분 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<aside class=\"aside\">\r\n");
      out.write("\t\t\t\t<h1>Online 연구소</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<nav class=\"menu text-menu first margin-top\">\r\n");
      out.write("\t\t\t\t\t<h1>메뉴</h1>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"current\"  href=\"/notice\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"\"  href=\"\">자주하는 질문</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"\" href=\"\">모임문의</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"\" href=\"\">이벤트/번개</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"menu\">\r\n");
      out.write("\t\t<h1>협력기관</h1>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a target=\"_blank\" href=\"http://www.tjvision.co.kr\"><img src=\"/resources/images/tjvision.png\" alt=\"비젼직업전문학교\" /></a></li>\r\n");
      out.write("            <li><a target=\"_blank\" href=\"https://www.sejongcommunity.com\"><img src=\"/resources/images/sejongcommunity.png\" alt=\"세종시 마을공동체지원센터\" /></a></li>                \r\n");
      out.write("            \t\t\t\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</aside>\r\n");
      out.write("\t\t\t<!-- --------------------------- main --------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<main>\r\n");
      out.write("                <h2 class=\"main title\">공지사항 등록</h2>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"breadcrumb\">\r\n");
      out.write("                    <h3 class=\"hidden\">breadlet</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>home</li>\r\n");
      out.write("                        <li>게시글 관리</li>\r\n");
      out.write("                        <li>공지사항</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <form method=\"post\" action=\"/notice/register\" >\r\n");
      out.write("                    <div class=\"margin-top first\">\r\n");
      out.write("                    \t<input type=\"hidden\" name=\"writerid\" value=\"kwonpro\">\r\n");
      out.write("                        <h3 class=\"hidden\">공지사항 입력</h3>\r\n");
      out.write("                        <table class=\"table\">\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>제목</th>\r\n");
      out.write("                                    <td class=\"text-align-left text-indent text-strong text-orange\" colspan=\"3\">\r\n");
      out.write("                                        <input type=\"text\" name=\"title\" />\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>첨부파일</th>\r\n");
      out.write("                                    <td colspan=\"3\" class=\"text-align-left text-indent\"><input type=\"file\"\r\n");
      out.write("                                            name=\"file\" /> </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr class=\"content\">\r\n");
      out.write("                                    <td colspan=\"4\"><textarea class=\"content\" name=\"content\"></textarea></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td colspan=\"4\" class=\"text-align-right\"><input class=\"vertical-align\" type=\"checkbox\" id=\"open\" name=\"open\" value=\"true\"><label for=\"open\" class=\"margin-left\">바로공개</label> </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"margin-top text-align-center\">\r\n");
      out.write("                        <input class=\"btn-text btn-default\" type=\"submit\" value=\"등록\" />\r\n");
      out.write("                        <a class=\"btn-text btn-cancel\" href=\"/notice\">취소</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("            </main>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("    <!-- ------------------- <footer> --------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <footer id=\"footer\">\r\n");
      out.write("        <div class=\"content-container\">\r\n");
      out.write("            <h2 id=\"footer-logo\"><img src=\"/resources/images/logo-footer.png\" alt=\"모임정보\"></h2>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"company-info\">\r\n");
      out.write("                <dl>\r\n");
      out.write("                    <dt>주소:</dt>\r\n");
      out.write("                    <dd>세종특별자치시 도움3로 160</dd>\r\n");
      out.write("                    <dt>관리자메일:</dt>\r\n");
      out.write("                    <dd>thinpig1130@gmail.com</dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("                <dl>\r\n");
      out.write("                    <dt>사업자 등록번호:</dt>\r\n");
      out.write("                    <dd>111-11-11111</dd>\r\n");
      out.write("                    <dt>비영리 단체:</dt>\r\n");
      out.write("                    <dd>세종시마을공동체 143호</dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("                <dl>\r\n");
      out.write("                    <dt>공동체명:</dt>\r\n");
      out.write("                    <dd>세종시프로그래머모임</dd>\r\n");
      out.write("                    <dt>대표:</dt>\r\n");
      out.write("                    <dd>권다애</dd>\r\n");
      out.write("                    <dt>전화번호:</dt>\r\n");
      out.write("                    <dd>010-4191-####</dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("                <div id=\"copyright\" class=\"margin-top\">Copyright ⓒ kwonpro.lec 2020-2020 All Right Reserved.\r\n");
      out.write("                    Contact thinpig1130@gmail.com for more information</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    </body>\r\n");
      out.write("    \r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/notice_write.jsp(55,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uid == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<nav id=\"acount-menu\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<h1 class=\"hidden\">회원메뉴</h1>\r\n");
          out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/member/login\">로그인</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/member/agree\">회원가입</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t</nav>\r\n");
          out.write("\t\t\t\t\t\t\t<nav id=\"member-menu\" class=\"linear-layout\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<h1 class=\"hidden\">고객메뉴</h1>\r\n");
          out.write("\t\t\t\t\t\t\t\t<ul class=\"linear-layout\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/notice\"><img\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"/resources/images/txt-customer.png\" alt=\"고객센터\" /></a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t</nav>\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<nav id=\"acount-menu\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<h1 class=\"hidden\">회원메뉴</h1>\r\n");
          out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${uid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 접속중</li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li> <a href=\"/member/logout\"> 로그아웃 </a> </li>\r\n");
          out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t</nav>\r\n");
          out.write("\t\t\t\t\t\t\t<nav id=\"member-menu\" class=\"linear-layout\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<h1 class=\"hidden\">고객메뉴</h1>\r\n");
          out.write("\t\t\t\t\t\t\t\t<ul class=\"linear-layout\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/\"><img\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"/resources/images/txt-mypage.png\" alt=\"마이페이지\" /></a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"/notice\"><img\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"/resources/images/txt-customer.png\" alt=\"고객센터\" /></a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t\t</nav>\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
